-- ② 표와 열 — 근거노트 다섯 칸 = evidence 표의 다섯 열
-- Supabase 대시보드 > SQL Editor 에 붙여 넣고 Run.
-- id · created_at 은 Table Editor 로 새 표를 만들 때 Supabase 가 자동으로 넣는 두 열과 같게 맞췄다.

create table if not exists public.evidence (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),       -- 저장 시각 (자동)

  item        text    not null,                          -- 항목 이름. 예) 제3종일반주거지역 용적률
  value       numeric,                                   -- 값. 숫자만 (300, '300% 이하' 아님)
  unit        text,                                      -- 단위. 예) %
  source      text    not null,                          -- 출처. 조문 번호 · 조례(법령) 번호 · 시행일
  queried_on  date    not null,                          -- 조회일. 오래된 값을 골라낼 수 있게 날짜형

  -- 3주차 값·단위 분리 규칙: 값이 있으면 단위도 있어야 함
  constraint evidence_value_needs_unit check (value is null or unit is not null)
);

comment on table  public.evidence            is '근거노트 — 항목·값·단위·출처·조회일';
comment on column public.evidence.item       is '항목 이름 (사람이 읽는 이름)';
comment on column public.evidence.value      is '값 — 숫자만. 글자로 넣으면 정렬·계산 불가';
comment on column public.evidence.unit       is '단위';
comment on column public.evidence.source     is '출처 — 조문 번호, 조례/법령 번호(MST), 시행일';
comment on column public.evidence.queried_on is '조회일';

-- 오래된 근거 골라내기용
create index if not exists evidence_queried_on_idx on public.evidence (queried_on);
